In [1]:
#importamos las librerias que vamos a necesitar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#leemos el archivo html y las tablas GDP per capita
datos =pd.read_html('https://en.wikipedia.org/wiki/Economy_of_the_United_States', match ='GDP per capita')
#Numero total de tablas con ese mismo nombre
len(datos)

2

In [9]:
datos[1]

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (inÂ % of GDP)
0,1980,2857.3,12552.9,2857.3,12552.9,-0.3%,13.5%,7.2%,NaN
1,1981,3207.0,13948.7,3207.0,13948.7,2.5%,10.4%,7.6%,NaN
2,1982,3343.8,14405.0,3343.8,14405.0,-1.8%,6.2%,9.7%,NaN
3,1983,3634.0,15513.7,3634.0,15513.7,4.6%,3.2%,9.6%,NaN
4,1984,4037.7,17086.4,4037.7,17086.4,7.2%,4.4%,7.5%,NaN
5,1985,4339.0,18199.3,4339.0,18199.3,4.2%,3.5%,7.2%,NaN
6,1986,4579.6,19034.8,4579.6,19034.8,3.5%,1.9%,7.0%,NaN
7,1987,4855.3,20001.0,4855.3,20001.0,3.5%,3.6%,6.2%,NaN
8,1988,5236.4,21376.0,5236.4,21376.0,4.2%,4.1%,5.5%,NaN
9,1989,5641.6,22814.1,5641.6,22814.1,3.7%,4.8%,5.3%,NaN
10,1990,5963.1,23848.0,5963.1,23848.0,1.9%,5.4%,5.6%,NaN
11,1991,6158.1,24302.8,6158.1,24302.8,-0.1%,4.2%,6.9%,NaN
12,1992,6520.3,25392.9,6520.3,25392.9,3.5%,3.0%,7.5%,NaN
13,1993,6858.6,26364.2,6858.6,26364.2,2.8%,3.0%,6.9%,NaN
14,1994,7287.3,27674.0,7287.3,27674.0,4.0%,2.6%,6.1%,NaN
15,1995,7639.8,28671.5,7639.8,28671.5,2.7%,2.8%,5.6%,NaN
16,1996,8073.1,29947.0,8073.1,29947.0,3.8%,2.9%,5.4%,NaN
17,1997,8577.6,31440.1,8577.6,31440.1,4.4%,2.3%,4.9%,NaN
18,1998,9062.8,32833.7,9062.8,32833.7,4.5%,1.5%,4.5%,NaN
19,1999,9631.2,34496.2,9631.2,34496.2,4.8%,2.2%,4.2%,NaN
20,2000,10251.0,36312.8,10251.0,36312.8,4.1%,3.4%,4.0%,NaN
21,2001,10581.9,37101.5,10581.9,37101.5,1.0%,2.8%,4.7%,53.1%
22,2002,10929.1,37945.8,10929.1,37945.8,1.7%,1.6%,5.8%,55.5%
23,2003,11456.5,39405.4,11456.5,39405.4,2.8%,2.3%,6.0%,58.6%
24,2004,12217.2,41641.6,12217.2,41641.6,3.9%,2.7%,5.5%,66.2%
25,2005,13039.2,44034.3,13039.2,44034.3,3.5%,3.4%,5.1%,65.5%
26,2006,13815.6,46216.9,13815.6,46216.9,2.8%,3.2%,4.6%,64.2%
27,2007,14474.3,47943.4,14474.3,47943.4,2.0%,2.9%,4.6%,64.6%
28,2008,14769.9,48470.6,14769.9,48470.6,0.1%,3.8%,5.8%,73.5%
29,2009,14478.1,47102.4,14478.1,47102.4,-2.6%,-0.3%,9.3%,86.7%
30,2010,15049.0,48586.3,15049.0,48586.3,2.7%,1.6%,9.6%,95.2%
31,2011,15599.7,50008.1,15599.7,50008.1,1.6%,3.1%,8.9%,99.5%
32,2012,16254.0,51736.7,16254.0,51736.7,2.3%,2.1%,8.1%,103.1%
33,2013,16843.2,53245.5,16843.2,53245.5,1.8%,1.5%,7.4%,104.6%
34,2014,17550.7,55083.5,17550.7,55083.5,2.3%,1.6%,6.2%,104.6%
35,2015,18206.0,56729.7,18206.0,56729.7,2.7%,0.1%,5.3%,105.2%
36,2016,18695.1,57840.0,18695.1,57840.0,1.7%,1.3%,4.9%,107.2%
37,2017,19477.4,59878.7,19477.4,59878.7,2.3%,2.1%,4.4%,106.2%
38,2018,20533.1,62787.8,20533.1,62787.8,2.9%,2.4%,3.9%,107.4%
39,2019,21381.0,65077.3,21381.0,65077.3,2.3%,1.8%,3.7%,108.8%
40,2020,21060.5,63577.3,21060.5,63577.3,-2.8%,1.2%,8.1%,133.4%
41,2021,23315.1,70159.8,23315.1,70159.8,5.9%,4.7%,5.4%,126.4%
42,2022,25464.5,76348.5,25464.5,76348.5,2.1%,8.0%,3.6%,121.7%
43,2023,26854.6,80034.6,26854.6,80034.6,1.6%,4.5%,3.8%,122.2%
44,2024,27741.1,82131.5,27741.1,82131.5,1.1%,2.3%,4.9%,126.0%
45,2025,28766.0,84600.7,28766.0,84600.7,1.8%,2.1%,4.8%,129.1%
46,2026,29902.9,87360.9,29902.9,87360.9,2.1%,2.0%,4.3%,132.0%
47,2027,31091.6,90231.1,31091.6,90231.1,2.1%,2.0%,4.1%,134.0%
48,2028,32349.7,93259.3,32349.7,93259.3,2.1%,2.0%,4.0%,136.2%

In [10]:
df=datos[1]

In [11]:
list(df)

['Year',
 'GDP (in Bil. US$PPP)',
 'GDP per capita (in US$ PPP)',
 'GDP (in Bil. US$nominal)',
 'GDP per capita (in US$ nominal)',
 'GDP growth (real)',
 'Inflation rate (in Percent)',
 'Unemployment (in Percent)',
 'Government debt (in\xa0% of GDP)']

In [13]:
#Eliminar columnas
df = df.drop(columns=['GDP (in Bil. US$PPP)','GDP per capita (in US$ PPP)'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Year                             49 non-null     int64
 1   GDP (in Bil. US$nominal)         49 non-null     float64
 2   GDP per capita (in US$ nominal)  49 non-null     float64
 3   GDP growth (real)                49 non-null     object
 4   Inflation rate (in Percent)      49 non-null     object
 5   Unemployment (in Percent)        49 non-null     object
 6   Government debt (inÂ % of GDP)    28 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 2.8+ KB

In [15]:
df.columns =['Year','GDP','GDP_Per_Capita','GDP_growth','Inflation_Rate','Unemployment','Government_Debt']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             49 non-null     int64
 1   GDP              49 non-null     float64
 2   GDP_Per_Capita   49 non-null     float64
 3   GDP_growth       49 non-null     object
 4   Inflation_Rate   49 non-null     object
 5   Unemployment     49 non-null     object
 6   Government_Debt  28 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 2.8+ KB

In [17]:
df['GDP_growth'] =df['GDP_growth'].replace({'%':''}, regex=True).astype('float')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             49 non-null     int64
 1   GDP              49 non-null     float64
 2   GDP_Per_Capita   49 non-null     float64
 3   GDP_growth       49 non-null     float64
 4   Inflation_Rate   49 non-null     object
 5   Unemployment     49 non-null     object
 6   Government_Debt  28 non-null     object
dtypes: float64(3), int64(1), object(3)
memory usage: 2.8+ KB

In [19]:
df['Inflation_Rate']=df['Inflation_Rate'].replace({'%':''}, regex=True).astype('float')

In [20]:
df['Unemployment']=df['Unemployment'].replace({'%':''}, regex=True).astype('float')

In [21]:
df['Government_Debt']=df['Government_Debt'].replace({'%':''}, regex=True).astype('float')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             49 non-null     int64
 1   GDP              49 non-null     float64
 2   GDP_Per_Capita   49 non-null     float64
 3   GDP_growth       49 non-null     float64
 4   Inflation_Rate   49 non-null     float64
 5   Unemployment     49 non-null     float64
 6   Government_Debt  28 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 2.8 KB

In [23]:
df.Government_Debt.isnull().sum()

21

In [24]:
df.head()

,Year,GDP,GDP_Per_Capita,GDP_growth,Inflation_Rate,Unemployment,Government_Debt
0,1980,2857.3,12552.9,-0.3,13.5,7.2,NaN
1,1981,3207.0,13948.7,2.5,10.4,7.6,NaN
2,1982,3343.8,14405.0,-1.8,6.2,9.7,NaN
3,1983,3634.0,15513.7,4.6,3.2,9.6,NaN
4,1984,4037.7,17086.4,7.2,4.4,7.5,NaN

In [25]:
df.to_csv('USA_economy.csv', index = False)

In [29]:
df.where( df.Inflation_Rate<10, 0)

,Year,GDP,GDP_Per_Capita,GDP_growth,Inflation_Rate,Unemployment,Government_Debt
0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.0,0.0,0.0,0.0,0.0,0.0
2,1982,3343.8,14405.0,-1.8,6.2,9.7,NaN
3,1983,3634.0,15513.7,4.6,3.2,9.6,NaN
4,1984,4037.7,17086.4,7.2,4.4,7.5,NaN
5,1985,4339.0,18199.3,4.2,3.5,7.2,NaN
6,1986,4579.6,19034.8,3.5,1.9,7.0,NaN
7,1987,4855.3,20001.0,3.5,3.6,6.2,NaN
8,1988,5236.4,21376.0,4.2,4.1,5.5,NaN
9,1989,5641.6,22814.1,3.7,4.8,5.3,NaN
10,1990,5963.1,23848.0,1.9,5.4,5.6,NaN
11,1991,6158.1,24302.8,-0.1,4.2,6.9,NaN
12,1992,6520.3,25392.9,3.5,3.0,7.5,NaN
13,1993,6858.6,26364.2,2.8,3.0,6.9,NaN
14,1994,7287.3,27674.0,4.0,2.6,6.1,NaN
15,1995,7639.8,28671.5,2.7,2.8,5.6,NaN
16,1996,8073.1,29947.0,3.8,2.9,5.4,NaN
17,1997,8577.6,31440.1,4.4,2.3,4.9,NaN
18,1998,9062.8,32833.7,4.5,1.5,4.5,NaN
19,1999,9631.2,34496.2,4.8,2.2,4.2,NaN
20,2000,10251.0,36312.8,4.1,3.4,4.0,NaN
21,2001,10581.9,37101.5,1.0,2.8,4.7,53.1
22,2002,10929.1,37945.8,1.7,1.6,5.8,55.5
23,2003,11456.5,39405.4,2.8,2.3,6.0,58.6
24,2004,12217.2,41641.6,3.9,2.7,5.5,66.2
25,2005,13039.2,44034.3,3.5,3.4,5.1,65.5
26,2006,13815.6,46216.9,2.8,3.2,4.6,64.2
27,2007,14474.3,47943.4,2.0,2.9,4.6,64.6
28,2008,14769.9,48470.6,0.1,3.8,5.8,73.5
29,2009,14478.1,47102.4,-2.6,-0.3,9.3,86.7
30,2010,15049.0,48586.3,2.7,1.6,9.6,95.2
31,2011,15599.7,50008.1,1.6,3.1,8.9,99.5
32,2012,16254.0,51736.7,2.3,2.1,8.1,103.1
33,2013,16843.2,53245.5,1.8,1.5,7.4,104.6
34,2014,17550.7,55083.5,2.3,1.6,6.2,104.6
35,2015,18206.0,56729.7,2.7,0.1,5.3,105.2
36,2016,18695.1,57840.0,1.7,1.3,4.9,107.2
37,2017,19477.4,59878.7,2.3,2.1,4.4,106.2
38,2018,20533.1,62787.8,2.9,2.4,3.9,107.4
39,2019,21381.0,65077.3,2.3,1.8,3.7,108.8
40,2020,21060.5,63577.3,-2.8,1.2,8.1,133.4
41,2021,23315.1,70159.8,5.9,4.7,5.4,126.4
42,2022,25464.5,76348.5,2.1,8.0,3.6,121.7
43,2023,26854.6,80034.6,1.6,4.5,3.8,122.2
44,2024,27741.1,82131.5,1.1,2.3,4.9,126.0
45,2025,28766.0,84600.7,1.8,2.1,4.8,129.1
46,2026,29902.9,87360.9,2.1,2.0,4.3,132.0
47,2027,31091.6,90231.1,2.1,2.0,4.1,134.0
48,2028,32349.7,93259.3,2.1,2.0,4.0,136.2